<?php

    use App\Eventbuizz\Database\EBSchema;
    use Illuminate\Database\Migrations\Migration;
    use Illuminate\Database\Schema\Blueprint;
    use Illuminate\Support\Facades\Schema;

    class CreateConfEventBadgesDesignTable extends Migration
    {
        const TABLE = 'conf_event_badges_design';

        /**
         * Run the migrations.
         *
         * @return void
         */
        public function up()
        {
            Schema::create(self::TABLE, function (Blueprint $table) {
                $table->bigInteger('id', true);
                $table->bigInteger('event_id')->index('event_id');
                $table->string('name');
                $table->string('type')->index('type');
                $table->integer('attendee_type');
                $table->string('width', 100);
                $table->string('height', 100);
                $table->tinyInteger('mirror')->default(0);
                $table->tinyInteger('is_default')->default(0);
                $table->longText('body');
                $table->tinyInteger('IsName')->default(0);
                $table->text('nameLocation');
                $table->tinyInteger('IsFirstName')->default(0);
                $table->text('firstnameLocation');
                $table->tinyInteger('IsLastName')->default(0);
                $table->text('lastnameLocation');
                $table->tinyInteger('IsCompanyName')->default(0);
                $table->text('companyNameLocation');
                $table->tinyInteger('IsTitle')->default(0);
                $table->text('titleLocation');
                $table->tinyInteger('IsCompanyAddress')->default(0);
                $table->text('companyAddressLocation');
                $table->tinyInteger('IsPrivateAddress')->default(0);
                $table->text('privateAddressLocation');
                $table->tinyInteger('IsTelephone')->default(0);
                $table->text('telephoneLocation');
                $table->tinyInteger('IsCompanyAddress_1');
                $table->string('companyAddressLocation_1');
                $table->tinyInteger('IsPrivateAddress_1');
                $table->string('privateAddressLocation_1', 254);
                $table->tinyInteger('IsTelephone_1');
                $table->string('telephoneLocation_1');
                $table->tinyInteger('IsMobile')->default(0)->comment('Use for drop down 1');
                $table->text('mobileLocation')->comment('Use for drop down 1 location');
                $table->tinyInteger('IsMobile_2')->default(0)->comment('Use for drop down 2');
                $table->text('mobile2Location')->comment('Use for drop down 2 location');
                $table->tinyInteger('IsMobile_3')->default(0)->comment('Use for drop down 3');
                $table->text('mobile3Location')->comment('Use for drop down 3 location');
                $table->tinyInteger('IsMobile_4')->default(0)->comment('Use for drop down 4');
                $table->text('mobile4Location')->comment('Use for drop down 4 location');
                $table->tinyInteger('IsMobile_5')->default(0)->comment('Use for drop down 5');
                $table->text('mobile5Location')->comment('Use for drop down 5 location');
                $table->tinyInteger('IsMobile_6')->default(0)->comment('Use for drop down 6');
                $table->text('mobile6Location')->comment('Use for drop down 6 location');
                $table->tinyInteger('IsMobile_7')->default(0)->comment('Use for drop down 7');
                $table->text('mobile7Location')->comment('Use for drop down 7 location');
                $table->tinyInteger('IsMobile_8')->default(0)->comment('Use for drop down 8');
                $table->text('mobile8Location')->comment('Use for drop down 8 location');
                $table->tinyInteger('IsMobile_9')->default(0)->comment('Use for drop down 9');
                $table->text('mobile9Location')->comment('Use for drop down 9 location');
                $table->tinyInteger('IsMobile_10')->default(0)->comment('Use for drop down 10');
                $table->text('mobile10Location')->comment('Use for drop down 10 location');
                $table->tinyInteger('Interests')->default(0);
                $table->text('interestsLocation');
                $table->tinyInteger('IsLogo')->default(0);
                $table->text('logoLocation');
                $table->tinyInteger('IsImage')->default(0);
                $table->text('imageLocation');
                $table->text('imageName');
                $table->tinyInteger('IsBgImage')->default(0);
                $table->text('bgImageLocation');
                $table->text('bgImageName');
                $table->tinyInteger('Textfield')->default(0);
                $table->text('textfieldLocation');
                $table->tinyInteger('IsEmail')->default(0);
                $table->text('emailLocation');
                $table->tinyInteger('IsProductArea')->default(0);
                $table->text('productAreaLocation');
                $table->tinyInteger('IsDepartment')->default(0);
                $table->text('departmentLocation');
                $table->tinyInteger('IsBarcode')->default(0);
                $table->text('barcodeLocation');
                $table->tinyInteger('IsCountry')->default(0);
                $table->text('countryLocation');
                $table->tinyInteger('IsOrganization')->default(0);
                $table->text('organizationLocation');
                $table->tinyInteger('IsDelegateNumber')->default(0);
                $table->text('delegateNumberLocation');
                $table->tinyInteger('IsNetworkGroup')->default(0);
                $table->text('networkGroupLocation');
                $table->tinyInteger('IsName_1')->default(0);
                $table->text('nameLocation_1');
                $table->tinyInteger('IsFirstName_1')->default(0);
                $table->text('firstnameLocation_1');
                $table->tinyInteger('IsLastName_1')->default(0);
                $table->text('lastnameLocation_1');
                $table->tinyInteger('IsCompanyName_1')->default(0);
                $table->text('companyNameLocation_1');
                $table->tinyInteger('IsTitle_1')->default(0);
                $table->text('titleLocation_1');
                $table->tinyInteger('IsBarcode_1')->default(0);
                $table->text('barcodeLocation_1');
                $table->tinyInteger('IsJobTask');
                $table->text('jobTaskLocation');
                $table->tinyInteger('IsInitial');
                $table->text('initialLocation');
                $table->tinyInteger('IsAge');
                $table->text('ageLocation');
                $table->tinyInteger('IsGender');
                $table->text('genderLocation');
                $table->tinyInteger('IsBirthDate');
                $table->text('birthDateLocation');
                $table->tinyInteger('IsDepartment1');
                $table->text('departmentLocation1');
                $table->tinyInteger('IsEmploymentDate');
                $table->text('employmentDateLocation');
                $table->tinyInteger('IsIndustry');
                $table->text('industryLocation');
                $table->tinyInteger('IsAbout');
                $table->text('aboutLocation');
                $table->tinyInteger('IsTableNumber');
                $table->text('tableNumberLocation');
                $table->tinyInteger('IsAttendeeGroups');
                $table->text('attendeeGroupsLocation');
                $table->tinyInteger('IsAttendeeType');
                $table->text('attendeeTypeLocation');
                $table->tinyInteger('IsJobTask_1');
                $table->string('jobTaskLocation_1');
                $table->tinyInteger('IsInitial_1');
                $table->string('initialLocation_1');
                $table->tinyInteger('IsAge_1');
                $table->string('ageLocation_1');
                $table->tinyInteger('IsGender_1');
                $table->string('genderLocation_1');
                $table->tinyInteger('IsBirthDate_1');
                $table->string('birthDateLocation_1');
                $table->tinyInteger('IsDepartment1_1');
                $table->string('departmentLocation1_1');
                $table->tinyInteger('IsEmploymentDate_1');
                $table->string('employmentDateLocation_1');
                $table->tinyInteger('IsIndustry_1');
                $table->string('industryLocation_1');
                $table->tinyInteger('IsAbout_1');
                $table->string('aboutLocation_1');
                $table->tinyInteger('IsTableNumber_1');
                $table->string('tableNumberLocation_1');
                $table->tinyInteger('IsAttendeeGroups_1');
                $table->string('attendeeGroupsLocation_1');
                $table->tinyInteger('IsAttendeeType_1');
                $table->string('attendeeTypeLocation_1');
                $table->tinyInteger('Textfield_1');
                $table->string('textfieldLocation_1');
                $table->tinyInteger('IsEmail_1');
                $table->string('emailLocation_1');
                $table->tinyInteger('IsCountry_1');
                $table->string('countryLocation_1');
                $table->tinyInteger('IsOrganization_1');
                $table->string('organizationLocation_1', 254);
                $table->tinyInteger('IsDelegateNumber_1');
                $table->string('delegateNumberLocation_1', 254);
                $table->tinyInteger('IsNetworkGroup_1');
                $table->string('networkGroupLocation_1');
                $table->tinyInteger('IsFirstNamePassport');
                $table->tinyInteger('IsFirstNamePassport_1');
                $table->tinyInteger('IsLastNamePassport');
                $table->tinyInteger('IsLastNamePassport_1');
                $table->tinyInteger('IsPlaceBirthPassport');
                $table->tinyInteger('IsPlaceBirthPassport_1');
                $table->tinyInteger('IsPassportNo');
                $table->tinyInteger('IsPassportNo_1');
                $table->tinyInteger('IsDateIssuePassport');
                $table->tinyInteger('IsDateIssuePassport_1');
                $table->tinyInteger('IsDateExpiryPassport');
                $table->tinyInteger('IsDateExpiryPassport_1');
                $table->tinyInteger('IsPrivateHouseNo');
                $table->tinyInteger('IsPrivateHouseNo_1');
                $table->tinyInteger('IsPrivateStreet');
                $table->tinyInteger('IsPrivateStreet_1');
                $table->tinyInteger('IsPrivatePostCode');
                $table->tinyInteger('IsPrivatePostCode_1');
                $table->tinyInteger('IsPrivateCity');
                $table->tinyInteger('IsPrivateCity_1');
                $table->tinyInteger('IsPrivateCountry');
                $table->tinyInteger('IsPrivateCountry_1');
                $table->text('firstNamePassportLocation');
                $table->text('firstNamePassportLocation_1');
                $table->text('lastNamePassportLocation');
                $table->text('lastNamePassportLocation_1');
                $table->text('placeBirthPassportLocation');
                $table->text('placeBirthPassportLocation_1');
                $table->text('passportNoLocation');
                $table->text('passportNoLocation_1');
                $table->text('dateIssuePassportLocation');
                $table->text('dateIssuePassportLocation_1');
                $table->text('dateExpiryPassportLocation');
                $table->text('dateExpiryPassportLocation_1');
                $table->text('privateHouseNoLocation');
                $table->text('privateHouseNoLocation_1');
                $table->text('privateStreetLocation');
                $table->text('privateStreetLocation_1');
                $table->text('privatePostCodeLocation');
                $table->text('privatePostCodeLocation_1');
                $table->text('privateCityLocation');
                $table->text('privateCityLocation_1');
                $table->text('privateCountryLocation');
                $table->text('privateCountryLocation_1');
                $table->tinyInteger('Interests_1')->default(0);
                $table->text('interestsLocation_1');
                $table->timestamps();
                $table->softDeletes();
            });


            if (app()->environment('live')) {
                Schema::connection(config('database.archive_connection'))->
                create(self::TABLE, function (Blueprint $table) {
                    $table->bigInteger('id');
                    $table->bigInteger('event_id')->index('event_id');
                    $table->string('name');
                    $table->string('type')->index('type');
                    $table->integer('attendee_type');
                    $table->string('width', 100);
                    $table->string('height', 100);
                    $table->tinyInteger('mirror')->default(0);
                    $table->tinyInteger('is_default')->default(0);
                    $table->longText('body');
                    $table->tinyInteger('IsName')->default(0);
                    $table->text('nameLocation');
                    $table->tinyInteger('IsFirstName')->default(0);
                    $table->text('firstnameLocation');
                    $table->tinyInteger('IsLastName')->default(0);
                    $table->text('lastnameLocation');
                    $table->tinyInteger('IsCompanyName')->default(0);
                    $table->text('companyNameLocation');
                    $table->tinyInteger('IsTitle')->default(0);
                    $table->text('titleLocation');
                    $table->tinyInteger('IsCompanyAddress')->default(0);
                    $table->text('companyAddressLocation');
                    $table->tinyInteger('IsPrivateAddress')->default(0);
                    $table->text('privateAddressLocation');
                    $table->tinyInteger('IsTelephone')->default(0);
                    $table->text('telephoneLocation');
                    $table->tinyInteger('IsCompanyAddress_1');
                    $table->string('companyAddressLocation_1');
                    $table->tinyInteger('IsPrivateAddress_1');
                    $table->string('privateAddressLocation_1', 254);
                    $table->tinyInteger('IsTelephone_1');
                    $table->string('telephoneLocation_1');
                    $table->tinyInteger('IsMobile')->default(0)->comment('Use for drop down 1');
                    $table->text('mobileLocation')->comment('Use for drop down 1 location');
                    $table->tinyInteger('IsMobile_2')->default(0)->comment('Use for drop down 2');
                    $table->text('mobile2Location')->comment('Use for drop down 2 location');
                    $table->tinyInteger('IsMobile_3')->default(0)->comment('Use for drop down 3');
                    $table->text('mobile3Location')->comment('Use for drop down 3 location');
                    $table->tinyInteger('IsMobile_4')->default(0)->comment('Use for drop down 4');
                    $table->text('mobile4Location')->comment('Use for drop down 4 location');
                    $table->tinyInteger('IsMobile_5')->default(0)->comment('Use for drop down 5');
                    $table->text('mobile5Location')->comment('Use for drop down 5 location');
                    $table->tinyInteger('IsMobile_6')->default(0)->comment('Use for drop down 6');
                    $table->text('mobile6Location')->comment('Use for drop down 6 location');
                    $table->tinyInteger('IsMobile_7')->default(0)->comment('Use for drop down 7');
                    $table->text('mobile7Location')->comment('Use for drop down 7 location');
                    $table->tinyInteger('IsMobile_8')->default(0)->comment('Use for drop down 8');
                    $table->text('mobile8Location')->comment('Use for drop down 8 location');
                    $table->tinyInteger('IsMobile_9')->default(0)->comment('Use for drop down 9');
                    $table->text('mobile9Location')->comment('Use for drop down 9 location');
                    $table->tinyInteger('IsMobile_10')->default(0)->comment('Use for drop down 10');
                    $table->text('mobile10Location')->comment('Use for drop down 10 location');
                    $table->tinyInteger('Interests')->default(0);
                    $table->text('interestsLocation');
                    $table->tinyInteger('IsLogo')->default(0);
                    $table->text('logoLocation');
                    $table->tinyInteger('IsImage')->default(0);
                    $table->text('imageLocation');
                    $table->text('imageName');
                    $table->tinyInteger('IsBgImage')->default(0);
                    $table->text('bgImageLocation');
                    $table->text('bgImageName');
                    $table->tinyInteger('Textfield')->default(0);
                    $table->text('textfieldLocation');
                    $table->tinyInteger('IsEmail')->default(0);
                    $table->text('emailLocation');
                    $table->tinyInteger('IsProductArea')->default(0);
                    $table->text('productAreaLocation');
                    $table->tinyInteger('IsDepartment')->default(0);
                    $table->text('departmentLocation');
                    $table->tinyInteger('IsBarcode')->default(0);
                    $table->text('barcodeLocation');
                    $table->tinyInteger('IsCountry')->default(0);
                    $table->text('countryLocation');
                    $table->tinyInteger('IsOrganization')->default(0);
                    $table->text('organizationLocation');
                    $table->tinyInteger('IsDelegateNumber')->default(0);
                    $table->text('delegateNumberLocation');
                    $table->tinyInteger('IsNetworkGroup')->default(0);
                    $table->text('networkGroupLocation');
                    $table->tinyInteger('IsName_1')->default(0);
                    $table->text('nameLocation_1');
                    $table->tinyInteger('IsFirstName_1')->default(0);
                    $table->text('firstnameLocation_1');
                    $table->tinyInteger('IsLastName_1')->default(0);
                    $table->text('lastnameLocation_1');
                    $table->tinyInteger('IsCompanyName_1')->default(0);
                    $table->text('companyNameLocation_1');
                    $table->tinyInteger('IsTitle_1')->default(0);
                    $table->text('titleLocation_1');
                    $table->tinyInteger('IsBarcode_1')->default(0);
                    $table->text('barcodeLocation_1');
                    $table->tinyInteger('IsJobTask');
                    $table->text('jobTaskLocation');
                    $table->tinyInteger('IsInitial');
                    $table->text('initialLocation');
                    $table->tinyInteger('IsAge');
                    $table->text('ageLocation');
                    $table->tinyInteger('IsGender');
                    $table->text('genderLocation');
                    $table->tinyInteger('IsBirthDate');
                    $table->text('birthDateLocation');
                    $table->tinyInteger('IsDepartment1');
                    $table->text('departmentLocation1');
                    $table->tinyInteger('IsEmploymentDate');
                    $table->text('employmentDateLocation');
                    $table->tinyInteger('IsIndustry');
                    $table->text('industryLocation');
                    $table->tinyInteger('IsAbout');
                    $table->text('aboutLocation');
                    $table->tinyInteger('IsTableNumber');
                    $table->text('tableNumberLocation');
                    $table->tinyInteger('IsAttendeeGroups');
                    $table->text('attendeeGroupsLocation');
                    $table->tinyInteger('IsAttendeeType');
                    $table->text('attendeeTypeLocation');
                    $table->tinyInteger('IsJobTask_1');
                    $table->string('jobTaskLocation_1');
                    $table->tinyInteger('IsInitial_1');
                    $table->string('initialLocation_1');
                    $table->tinyInteger('IsAge_1');
                    $table->string('ageLocation_1');
                    $table->tinyInteger('IsGender_1');
                    $table->string('genderLocation_1');
                    $table->tinyInteger('IsBirthDate_1');
                    $table->string('birthDateLocation_1');
                    $table->tinyInteger('IsDepartment1_1');
                    $table->string('departmentLocation1_1');
                    $table->tinyInteger('IsEmploymentDate_1');
                    $table->string('employmentDateLocation_1');
                    $table->tinyInteger('IsIndustry_1');
                    $table->string('industryLocation_1');
                    $table->tinyInteger('IsAbout_1');
                    $table->string('aboutLocation_1');
                    $table->tinyInteger('IsTableNumber_1');
                    $table->string('tableNumberLocation_1');
                    $table->tinyInteger('IsAttendeeGroups_1');
                    $table->string('attendeeGroupsLocation_1');
                    $table->tinyInteger('IsAttendeeType_1');
                    $table->string('attendeeTypeLocation_1');
                    $table->tinyInteger('Textfield_1');
                    $table->string('textfieldLocation_1');
                    $table->tinyInteger('IsEmail_1');
                    $table->string('emailLocation_1');
                    $table->tinyInteger('IsCountry_1');
                    $table->string('countryLocation_1');
                    $table->tinyInteger('IsOrganization_1');
                    $table->string('organizationLocation_1', 254);
                    $table->tinyInteger('IsDelegateNumber_1');
                    $table->string('delegateNumberLocation_1', 254);
                    $table->tinyInteger('IsNetworkGroup_1');
                    $table->string('networkGroupLocation_1');
                    $table->tinyInteger('IsFirstNamePassport');
                    $table->tinyInteger('IsFirstNamePassport_1');
                    $table->tinyInteger('IsLastNamePassport');
                    $table->tinyInteger('IsLastNamePassport_1');
                    $table->tinyInteger('IsPlaceBirthPassport');
                    $table->tinyInteger('IsPlaceBirthPassport_1');
                    $table->tinyInteger('IsPassportNo');
                    $table->tinyInteger('IsPassportNo_1');
                    $table->tinyInteger('IsDateIssuePassport');
                    $table->tinyInteger('IsDateIssuePassport_1');
                    $table->tinyInteger('IsDateExpiryPassport');
                    $table->tinyInteger('IsDateExpiryPassport_1');
                    $table->tinyInteger('IsPrivateHouseNo');
                    $table->tinyInteger('IsPrivateHouseNo_1');
                    $table->tinyInteger('IsPrivateStreet');
                    $table->tinyInteger('IsPrivateStreet_1');
                    $table->tinyInteger('IsPrivatePostCode');
                    $table->tinyInteger('IsPrivatePostCode_1');
                    $table->tinyInteger('IsPrivateCity');
                    $table->tinyInteger('IsPrivateCity_1');
                    $table->tinyInteger('IsPrivateCountry');
                    $table->tinyInteger('IsPrivateCountry_1');
                    $table->text('firstNamePassportLocation');
                    $table->text('firstNamePassportLocation_1');
                    $table->text('lastNamePassportLocation');
                    $table->text('lastNamePassportLocation_1');
                    $table->text('placeBirthPassportLocation');
                    $table->text('placeBirthPassportLocation_1');
                    $table->text('passportNoLocation');
                    $table->text('passportNoLocation_1');
                    $table->text('dateIssuePassportLocation');
                    $table->text('dateIssuePassportLocation_1');
                    $table->text('dateExpiryPassportLocation');
                    $table->text('dateExpiryPassportLocation_1');
                    $table->text('privateHouseNoLocation');
                    $table->text('privateHouseNoLocation_1');
                    $table->text('privateStreetLocation');
                    $table->text('privateStreetLocation_1');
                    $table->text('privatePostCodeLocation');
                    $table->text('privatePostCodeLocation_1');
                    $table->text('privateCityLocation');
                    $table->text('privateCityLocation_1');
                    $table->text('privateCountryLocation');
                    $table->text('privateCountryLocation_1');
                    $table->tinyInteger('Interests_1')->default(0);
                    $table->text('interestsLocation_1');
                    $table->timestamps();
                    $table->softDeletes();
                });

                EBSchema::createBeforeDeleteTrigger(self::TABLE);
            }


        }

        /**
         * Reverse the migrations.
         *
         * @return void
         */
        public function down()
        {
            EBSchema::dropDeleteTrigger(self::TABLE);
            Schema::dropIfExists(self::TABLE);
            Schema::connection(config('database.archive_connection'))->dropIfExists(self::TABLE);
        }
    }
